imports:
    - { resource: "services/installer.yml" }

services:
  newsletter_definition.controller.admin:
    class: NewsletterDefinitionBundle\Controller\NewsletterDefinitionController

  newsletter_definition.sql_renderer:
    class: NewsletterDefinitionBundle\SqlRenderer\Renderer
    arguments:
      - '@doctrine.dbal.default_connection'
  pimcore.document.newsletter.factory.newsletter_definition:
    class: Pimcore\Document\Newsletter\DefaultAddressSourceAdapterFactory
    arguments:
      - 'NewsletterDefinitionBundle\AddressSourceAdapater\DefinitionAddressSourceAdapter'